---
name: see webhook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - env:
          CONTEXT: ${{ toJson(github) }}
        run: |
          jq . <<< $CONTEXT
